# Generated by Django 5.0 on 2024-11-22 09:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_businessprofile_incorporation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_full_na_5acde0_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='employer_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='employer_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='employer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='customers/profile_pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_number'], name='customers_c_id_numb_543491_idx'),
        ),
    ]
