# Generated by Django 5.0 on 2024-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_set_default_email_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
