# Generated by Django 5.0 on 2024-11-29 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PROFILE_UPDATE', 'Profile Update'), ('ROLE_CHANGE', 'Role Change'), ('ACCOUNT_CREATE', 'Account Creation'), ('ACCOUNT_DISABLE', 'Account Disabled'), ('ACCOUNT_ENABLE', 'Account Enabled'), ('MFA_ENABLE', 'MFA Enabled'), ('MFA_DISABLE', 'MFA Disabled')], max_length=50)),
                ('event_description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('WARNING', 'Warning')], max_length=20)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx'), models.Index(fields=['event_type', '-created_at'], name='accounts_au_event_t_03bfa1_idx'), models.Index(fields=['-created_at'], name='accounts_au_created_721afe_idx')],
            },
        ),
    ]
