Table users {
  id int [pk, increment]
  username varchar(255)
  password varchar(255)
  email varchar(255)
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  login_attempts int [default: 0]
  reset_token varchar(255) [default: null]
  reset_requested_at datetime [default: null]
  last_attempt timestamp [default: `CURRENT_TIMESTAMP`]
}

Table borrowers {
  id int [pk, increment]
  firstName varchar(255)
  lastName varchar(255)
  nationalId int(8) [unique]
  occupation varchar(255)
  city varchar(255)
  county varchar(255)
  mobileNumber varchar(10)
  email varchar(255)
  dob date
  age int [default: 0]
}

Table loans {
  loan_num int [pk, increment]
  loan_amount int
  interest_rate int
  loan_period int
  borrower_id int
  loan_type varchar(255)
  loan_status varchar(255) [default: 'Active']
  loan_date date
  due_date date
  closure_date date [default: null]
  penalty_amount decimal(10,2) [default: 0.00]
  loan_balance int

  Foreign Key: borrower_id -> borrowers.nationalId
}

Table repayments {
  txn_id int [pk, increment]
  loan_num int
  repayment_amount int
  repayment_date date
  repayment_status varchar(255)
  borrower_id int

  Foreign Key: loan_num -> loans.loan_num
  Foreign Key: borrower_id -> borrowers.nationalId
}