# Generated by Django 4.2.17 on 2024-12-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_loan_repayment_schedule_alter_repaymentschedule_loan'),
        ('transactions', '0003_remove_transaction_description_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_repayment_schedules', to='loans.loan'),
        ),
    ]
