# Generated by Django 4.2.17 on 2024-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanguarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantor',
            name='id_document',
            field=models.CharField(blank=True, help_text="Path to guarantor's ID document (optional)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='income_proof',
            field=models.CharField(blank=True, help_text="Path to guarantor's income proof (optional)", max_length=255, null=True),
        ),
    ]
