# Generated by Django 4.2.17 on 2024-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loanproduct_eligibility_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, help_text='Requested date for loan disbursement', null=True),
        ),
    ]
