# Generated by Django 4.2.17 on 2024-12-07 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_loanapplication_disbursement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS_OWNER', 'Business Owner'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('STUDENT', 'Student')], help_text='Current employment status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income in base currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
