# Generated by Django 4.2.17 on 2024-12-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_alter_repaymentschedule_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_schedule',
            field=models.ManyToManyField(blank=True, related_name='loans_repayment_schedules', to='loans.repaymentschedule'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayment_schedules', to='loans.loan'),
        ),
    ]
